runtime: python312

entrypoint: gunicorn -b :$PORT run:app

instance_class: F2

env_variables:
  FLASK_ENV: production
  SECRET_KEY: "your-secret-key"

handlers:
  - url: /static
    static_dir: static/

  - url: /.*
    script: auto

